version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    restart: always
    env_file: .env
    init: true
    volumes: 
      - db_data:/var/lib/mysql
    networks: 
      - inception_net

  wordpress:
    depends_on: 
      - mariadb
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1.0
    restart: always
    env_file: .env
    init: true
    volumes: 
      - wp_data:/var/www/html
    networks: 
      - inception_net

  nginx:
    depends_on: 
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1.0
    restart: always
    ports: 
      - "80:80"
    init: true
    volumes: 
      - wp_data:/var/www/html
    networks: 
      - inception_net

volumes:
  wp_data:
  db_data:

networks:
  inception_net:
    driver: bridge